#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

NAME = CardinalMini
CARDINAL_VARIANT = mini
WINDOWS_ICON_RC = distrho-mini.rc
include ../Makefile.cardinal.mk
