#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

NAME = CardinalNative
CARDINAL_VARIANT = native
WINDOWS_ICON_RC = distrho-native.rc
include ../Makefile.cardinal.mk
